const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app/static/app.js','utf8');
const elements={}; const $=id=>elements[id]??={value:'',checked:false,disabled:false,pause(){this.paused=true},removeAttribute(){this.cleared=true},load(){this.loaded=true}};
const pp={enabled:true,eq_enabled:true,eq_preset:'soften',frequency:3500,gain_db:-1.5,q:1,peak_enabled:true,peak_dbfs:-1};
let stopped=0,synced=0;
const ctx=vm.createContext({$,busy:false,state:{settings:{post_processing:pp},job:{running:false}},project:{id:'project',rows:[{id:1,generated_at:'same',pause_ms:0}]},saving:Promise.resolve(),guard:fn=>fn,json:(method,data)=>({method,data}),api:async(path,options)=>path==='/settings/post_processing'?{post_processing:options.data}:ctx.project,playback:{stop(){stopped++}},syncProject(){synced++},message(){},document:{getElementById:$,querySelectorAll:()=>[]}});
vm.runInContext(fs.readFileSync('app/static/shared_library.js','utf8'),ctx);
vm.runInContext(source.slice(0,source.indexOf('const $=')),ctx);
vm.runInContext(source.slice(source.indexOf('const EQ_PRESETS'),source.indexOf("$('ppPlayBefore')")),ctx);
vm.runInContext(source.slice(source.indexOf('function updateJob()'),source.indexOf('async function startGeneration')),ctx);
(async()=>{
 ctx.renderPostProcessing();ctx.updateJob();assert.equal($('eqGain').disabled,true);
 $('eqPreset').value='custom';ctx.updateEqPresetFields();$('eqGain').value=-6;ctx.updateJob();assert.equal($('eqGain').disabled,false);assert.equal($('eqGain').value,-6);
 const row=ctx.project.rows[0],before=ctx.audioUrl('project',row),raw=ctx.audioUrl('project',row,'raw');
 await $('savePostProcessing').onclick();assert.notEqual(ctx.audioUrl('project',row),before);assert.equal(ctx.audioUrl('project',row,'raw'),raw);assert.equal(stopped,1);assert.equal(synced,1);assert.equal($('ppPreviewAudio').cleared,true);
 ctx.state.settings.post_processing={...pp,eq_preset:'soften',gain_db:-6};ctx.renderPostProcessing();assert.equal($('eqPreset').value,'custom');assert.equal($('eqGain').value,-6);
 ctx.state.operation={id:'one',project:'project',kind:'generate'};ctx.state.job.running=true;ctx.updateJob();assert.equal($('eqGain').disabled,true);
 ctx.state.shared_library=true;ctx.state.operation=null;ctx.state.job.running=false;ctx.updateJob();assert.equal($('saveDictionary').disabled,true);assert.equal($('registerMaster').disabled,true);assert.equal($('saveSettings').disabled,false);ctx.state.operation={id:'one',project:'project',kind:'generate'};ctx.state.job.running=true;ctx.updateJob();ctx.state.operation=null;ctx.state.job.running=false;ctx.updateJob();assert.equal($('addWord').disabled,true);assert.equal($('sharedDictionaryNotice').hidden,false);
 ctx.state.shared_library=false;ctx.state.operation={id:'other',project:'another-project',kind:'generate'};ctx.updateJob();assert.equal($('stopGeneration').disabled,true);assert.equal($('addRow').disabled,false);assert.equal($('generate').disabled,true);ctx.state.operation={id:'own',project:'project',kind:'export'};ctx.updateJob();assert.equal($('stopGeneration').disabled,false);assert.equal($('addRow').disabled,true);
 console.log('PP cache keys, player reset, preset polling and legacy saved values: OK');
})().catch(e=>{console.error(e);process.exitCode=1});
